### ISSUE TITLE
GoogleLinks Feature

### ISSUE THREAD

**Issue by HassanChowdhry** [HassanChowdhry/GoogleLinks#3]
![Home Page](https://user-images.githubusercontent.com/94680098/167965006-4d95cf85-7ecb-42e3-9430-d3493305844b.png)

**Comment by HassanChowdhry** [comment]
# Updated Design

![GoogleLinks v2](https://user-images.githubusercontent.com/94680098/167866637-84f2adb0-33c3-45b0-883e-8dd7260adfd0.png)

![Home](https://user-images.githubusercontent.com/94680098/167866586-1d560f91-a698-4366-af5b-23d7e36a31df.png)

![after creation_](https://user-images.githubusercontent.com/94680098/167866645-946108c5-cf8d-4a50-89ea-def5be6ed97b.png)

**Comment by HassanChowdhry** [comment]
# update for new mocks

![GoogleLinks v2](https://user-images.githubusercontent.com/94680098/167966846-dde37536-e9a9-4393-8a74-6185926291bf.png)

![Home](https://user-images.githubusercontent.com/94680098/167966862-c35de3aa-7f04-40f1-9886-85462587ddfa.png)

![after creation_](https://user-images.githubusercontent.com/94680098/167966874-c4042fa2-856d-40a0-b02b-b1a85965b78b.png)

**Comment by BilalIshtiaque** [comment]
Instead of `Create Excel` button in the 2nd page, just name it `Download File` or something

**Comment by HassanChowdhry** [comment]
# small fixes

![GoogleLinks v2](https://user-images.githubusercontent.com/94680098/168113994-8f192370-514d-404c-9c61-5875f0d9b1a1.png)

![Home](https://user-images.githubusercontent.com/94680098/168114006-79dd922f-b7a4-4b0c-9dc1-b352aa41826c.png)

![after creation_](https://user-images.githubusercontent.com/94680098/168114015-772f15ea-214a-42fa-b0fb-0d2ca2973fbb.png)
